Adding up of comment and Aligning
creativecommons/quantifying pull request #51
Opened 2023-03-31 16:19 UTC by NEGRAH-S

## Fixes
- Edited the indentation of codes.
- Added more comment for easy Understanding.
- Overall made it efficient in term of space.

## Description
Through this Pull Request (PR) the code is represented in more systematic and pure manner along with addition of comments it has been made readable than before.

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [ x] My commit messages follow [best practices][best_practices].
- [ x] My code follows the established code style of the repository.
- [ x] I added or updated tests for the changes I made (if applicable).
- [ x] I added or updated documentation (if applicable).
- [ x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-03-31 18:50 UTC, satyampsoni requested changes

2023-03-31 18:50 UTC, satyampsoni commented on internetarchive/internetarchive_scratcher.py
> +# Impor Standard library
t in Import is missing here.

2023-03-31 18:50 UTC, satyampsoni commented on vimeo/vimeo_scratcher.py
> +# List of License
Replace license with licenses.

2023-03-31 18:50 UTC, satyampsoni commented on vimeo/vimeo_scratcher.py
> +# Storing License
Replace license with licenses

2023-03-31 18:50 UTC, satyampsoni commented on wikicommons/wikicommons_scratcher.py
> +# Categories
I think categories should be replaced with subcategories here.

2023-04-23 07:03 UTC, NEGRAH-S commented
> This project has tooling for style/syntax. This PR conflicts with it.
> 
> If your environment is setup correctly, you can run:
> 
> ```shell
> ./dev/tools.sh
> ```
> 
> Also see [Tooling](https://github.com/creativecommons/quantifying#tooling) section of README.
> 
> (I also added issue #53)

ookh sir I got ur point will refer to details u shared.

2023-10-26 20:02 UTC, closed without merging